name: Build and push to Docker.io

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New Image Tag'
        required: true
        default: '1.0.0'
        type: string

jobs:
  build:
    name: Build & push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hash needed apps json file
        id: base64Var
        run: |
          APPS_JSON=$(<apps.json)
          APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 -w 0)
          echo "APPS_JSON_BASE64=$APPS_JSON_BASE64" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        if: ${{ inputs.push }}
        uses: docker/bake-action@v4.1.0
        with:
          push: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/custom/Containerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dmshd:${{ inputs.tag }}
          build-args: |
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-15
            PYTHON_VERSION=3.11.6
            NODE_VERSION=18.18.2
            APPS_JSON_BASE64=${{ steps.base64Var.outputs.APPS_JSON_BASE64 }}
          push: true
